### ISSUE TITLE
Get GPMF on large files

### ISSUE THREAD

**Issue by tkhyn** [JuanIrache/gpmf-extract#20]
Hi,

Not an issue, but a resolution. This might make gpmf-extract redundant. I use the following, simply leveraging ffprobe and ffmpeg. The returned raw data can be directly passed to gopro-telemetry (thanks for this by the way!).

Requires ffprobe-installer, ffmpeg-installer, ffprobe-client, fluent-ffmpeg.

```javascript

process.env.FFPROBE_PATH = require('@ffprobe-installer/ffprobe').path;
const ffprobe = require('ffprobe-client');

const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfmpegPath(require('@ffmpeg-installer/ffmpeg').path);

const extractGPMF = async videoFile => {
  const ffData = await ffprobe(videoFile);

  let gpsData = null;
  for (let i = 0; i < ffData.streams.length; i++) {
    if (ffData.streams[i].codec_tag_string === 'gpmd') {
      return await extractGPMFAt(videoFile, i);
    }
  }
  return null;
};

const extractGPMFAt = async (videoFile, stream) => {
  let rawData = Buffer.alloc(0);
  await new Promise(resolve => {
    ffmpeg(videoFile)
      .outputOption('-y')
      .outputOptions('-codec copy')
      .outputOptions(`-map 0:${stream}`)
      .outputOption('-f rawvideo')
      .pipe()
      .on('data', chunk => {
        rawData = Buffer.concat([rawData, chunk]);
      }).on('end', resolve);
  });
  return rawData;
};

```

**Comment by JuanIrache** [comment]
Cool, that's an interesting way to do this mostly in JavaScript. I'm assuming it won't work on the browser, though.

Will close this as, as you say, it's not really an issue. Thanks!

**Comment by tkhyn** [comment]
@JuanIrache indeed, it's unlikely to work in the browser. On the other hand isn't it unlikely to see a very large file processed in the browser. Maybe this can be used as a fallback when running in node and the file is too big?

**Comment by urbste** [comment]
@tkhyn Hi, I do have this exact problem as I want to extract the Telemetry from a large file. However, I am not very familiar with JavaScript and I used @JuanIrache tool for smaller GoPro files before. 

I wrote a small .js file that can extract the telemetry data and save it to a json file:

``` javascript
const file = fs.readFileSync(video_path);
gpmfExtract(file)
  .then(extracted => {
    let telemetry = goproTelemetry(extracted, 
      { stream: ['ACCL','GPS5','GYRO','SHUT','MAGN','SCEN','GPSP','GPSF'], 
      ellipsoid: true, geoidHeight: true, repeatSticky: true });
    fs.writeFileSync(
      output_file, JSON.stringify(telemetry, null, '\t'));
    console.log('Telemetry saved as JSON');
  })
  .catch(error => console.log(error));
```

How would I use your proposed function? I tried to change the line
```javascript
gpmfExtract(file)
```
to 
```javascript
extractGPMF(video_path)
```

However I get an error 
```bash
TypeError: Cannot read property 'length' of undefined
    at parseKLV (/home/steffen/Projects/GoProMetadataExtractor/node_modules/gopro-telemetry/code/parseKLV.js:30:14)
    at parseOne (/home/steffen/Projects/GoProMetadataExtractor/node_modules/gopro-telemetry/index.js:26:18)
    at process (/home/steffen/Projects/GoProMetadataExtractor/node_modules/gopro-telemetry/index.js:102:20)
    at module.exports (/home/steffen/Projects/GoProMetadataExtractor/node_modules/gopro-telemetry/index.js:204:10)
    at extractGPMF.then.extracted (/home/steffen/Projects/GoProMetadataExtractor/extract_metadata_from_video.js:63:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Do I use the function wrong?

Cheers
Steffen

**Comment by urbste** [comment]
Found a solution for this issue. Greate repo: https://github.com/kws/GoProTelemetryExtract

**Comment by ZainUlMustafa** [comment]
For those facing this issue, I readjusted the code provided by @tkhyn and it worked for me on a 3.7 GB video.
Here is a direct link: https://github.com/ZainUlMustafa/GoPro-Telemetry-Tests/blob/main/TelemetryTests/alt_index.js

**Comment by mattwynyard** [comment]
Thanks @tkhyn

**Comment by MrCsabaToth** [comment]
Ok, but what are we supposed to do with the resulting bin file which contains the metadata FOURCC info chunks? Because I also get `TypeError: Cannot read property 'length' of undefined`
