### ISSUE TITLE
Track not found

### ISSUE THREAD

**Issue by bknill** [JuanIrache/gpmf-extract#37]
In the browser on large files I'm getting a 'Track not found' error, then progress increasing for ever to very large numbers. 
![image](https://user-images.githubusercontent.com/7074483/95960416-32641080-0e60-11eb-94b0-c25a9a4ff459.png)
(upto 60k + at now)

Is this working and just taking a long time?

**Comment by JuanIrache** [comment]
Hello,

Thanks for the report. I am unable to reproduce your issue with 4GB files. How large are yours?

Would you be able to provide a minimal project to reproduce the issue?

**Comment by bknill** [comment]
160mb.

const telemetry = yield call(VideoService.extractRotation, action.asset)
const result = await gpmfExtract(asset.file, true,d => console.log(d))
        const telemetry = await goproTelemetry(result, {stream : ['ACCL','GYRO', "MAGN"]});

Shall I email you an example video file? it's a 360 from a Go Pro Max. 

I tried with like a 10mb file and it works well really quickly. 

I left it running overnight and it's at 196k!

**Comment by bknill** [comment]
Possibly these files don't have telemetry, they're not working on your free version (however my small files are). There must be a setting which possibly disables in it the Max when the footage is stabalised or stitched for 360?

**Comment by bknill** [comment]
But I presume the bug is that the progress counter keeps going even when the file fails.

I just tried with the original .360 file from the Go Pro and it's working great.

**Comment by JuanIrache** [comment]
That makes sense. Could you send me one of those files anyway so I see what's happening? And try to stop the process when it fails.

It's very very rare that a file contains no telemetry at all. Are you sure these are files taken straight from the camera? Not processed with any other software?

Thanks

**Comment by bknill** [comment]
they're not. They're processed with the Go Pro Max Exporter to stitch the 360 video. In the Mac version it includes the Telemetry data apparently in the exported video, in the Windows app it doesn't. 

Shall I email you one?

**Comment by JuanIrache** [comment]
That must be it. But yes, if you could send me one anyway I'll see what I can improve.
app@prototyping.barcelona

Thanks
