### ISSUE TITLE
use in React Native projects

### ISSUE THREAD

**Issue by ShaneZhengNZ** [JuanIrache/gpmf-extract#54]
I am trying to use this package in a React Native project, however, it complains about the 'Buffer'.

Can we fix this so that it somehow supports in a RN environment?

**Comment by JuanIrache** [comment]
Hi @ShaneZhengNZ ,

I have never used React Native before. I don't think I can help you there, but if you are able to send a PR that fixes and keeps things stable, merging it shouldn't be a problem.

**Comment by Akxe** [comment]
This should be fixed now, as the library is now fully browser compliant.
