### ISSUE TITLE
Update `mp4box` to fix browser errors

### ISSUE THREAD

**Issue by Akxe** [JuanIrache/gpmf-extract#61]
Hi, in a recent try to get GPS data from a GoPro video, I found out that there are multiple errors. One that can be fixed when the `mp4box` is updated is the **ReferenceError: ref is not defined`**.

Others might come later... 

It looks to me like there is not enough testing done on the browser, as it requires a lot of polyfills or workarounds. Try running the library in a `"strict"` mode and without any polyfills to see what needs to be fixed. (I am not against using polyfill, but I would like to know I have to use one in order to have it working)

PS: I would consider buying the pro license as a "priority support" to get the GPS extraction working on the browser. (Also please add types?)

**Comment by JuanIrache** [comment]
Sounds good. I seem to remember some versions of mp4box caused issues. I haven't tested them in a long time.

The module was conceived to be bundled, but PRs that improve straight browser usage are welcome.
